name: f_coffee_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter

  # State management and depency injection
  flutter_riverpod: 2.6.1
  # For SVG images
  flutter_svg: 2.1.0
  # Number format
  intl: 0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/coffee/
   - assets/images/svg/

  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic          
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600   
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic   
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700  
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700  
          style: italic          
